RuRenter.ru Member's Terms & Conditions
	

Quick easy to understand summary of  our promises to you

A. We’ll market your property throughout our network of sites

B. You can set your prices in Russian roubles, USD or Euro.

C. We’ll charge you 10%  commission on the total booking value if we get you a booking

D. We’ll charge you just 2% if it’s your booking and you process the payments through our system

E. Once a booking has had the deposit paid, you are contracted to us and the customer

F. This means you’ll be charged our commission on the full booking value whether or not it’s subsequently cancelled by either party.

G. If you cancel a contracted booking we’ll charge you an additional 50 EUR cancellation fee

H. Payments for your bookings will be available for you to request online 3 days after your customer’s holiday has started. For your very first booking with us however you will need to wait until the day after the holiday ends and it is also subject to you having waited at least 4 weeks from the first payment made to us for a booking at your property.

I. For subsequent bookings after the first booking has completed and after 28 days has passed from the first customer payment, you are then able to request  early payment although there is an extra charge for this.  The charge is 1.5% of the booking value if payment is requested within 4 weeks of us receiving the Customer’s payment, or 1% of the booking value if payment is requested after 4 weeks of us receiving the Customer’s payment.

J. In addition to our charges to you we also levy a booking charge on your customer. We also charge them a credit/debit card processing fee. We closely monitor these fees to keep them as low as possible to maximize bookings.

K. We also provide your customers with the option of a low cost non-refundable breakage waiver instead of paying a refundable deposit. This indemnifies you against any breakage claim up to your requested breakage deposit value.

Comprehensive terms and conditions and small print from our lawyers

By ticking "Accept" and the "Continue" button at the foot of this page "You" are consenting to be bound by all of these Terms and Conditions.

This Agreement is between

1. Mr. {name}, and RuRenter Ltd UAB t/as RuRenter whose registered office is Eisiskiu Sodu 5-Oij G. 19, Vilniaus, Lietuva referred to in this Agreement  as “Us” or “We” “You” means the person who has joined as a member of RuRenter who either owns or co-owns the Accommodation or who is the authorised agent of the owner(s) of the Accommodation and in either case, has the permission of all owners of the Accommodation to market and let the Accommodation for holiday purposes in accordance with this Agreement.

Commencement Date

1.1 This agreement commences on the date on which You click the "I Accept"; button below. We confirm and agree that following acceptance of these Terms and Conditions You will be given access to and use of the System as specified by Us in return for payment by You of the commission set out in the schedule.

Definitions and Interpretation

2. The following words and expressions shall have the following meanings unless the context otherwise requires:-

2.1 "Accommodation" means any and all hotels, apartment blocks, apartments, houses or other accommodation building or otherwise occupied by any Customers including the accommodation premises, any swimming pool(s), ancillary building(s), annex(es), all contents, fixtures and fittings, grounds, facilities and services (both inside and outside) available or accessible to any Customers as offered for holiday letting by You.
2.2 “Agreement” means these Terms and Conditions (including the Schedule) as modified and/or added to by Us from time to time.

2.3 “Commission” means the commission payable by You in accordance with this Agreement (including the Schedule) on all bookings of Your Accommodation made via the System.

2.4 "Customer(s)" means any and all person(s) who book the Accommodation through the System.

2.5 “RuRenter Affiliate program” means the affiliate program set up and administered by Us.

2.6 “RuRenter Affiliate program booking” means any booking that is generated by a member of the RuRenter Affiliate program. In essence these bookings are treated in exactly the same way as if they were generated directly by Us.

2.7 “System” means the online software provided on the Website. The System provides You with the ability to set up a rental contract, a booking engine and a pricing and discounting system. It also provides You with the ability to create a website for a single property, a series of properties or a packaged portfolio of properties. Additionally the booking engine has an interface for Your Customers to book and pay for their bookings online by credit and/or debit card. By booking and paying through the System Your Customers expressly agree to the rental contract that you have set up through the System.
2.8 “Website” means any website(s) owned and controlled by Us through which You can offer the Accommodation for holiday lets.

2.9 “Client Account” means the designated bank account maintained by Us with a UK banking organisation solely for the purpose of depositing funds collected by Us from Customers who pay for Accommodation bookings by credit or debit card. This account is entirely separate from any other commercial or business activity.

2.10 “Customer Funds” means the monies collected by Us from Customers who pay by credit or debit card through the System.

2.11 “Immediate Early Payment” means Customer Funds collected by You from the Client Account at anytime prior to the completion of the stay to which the Customer Funds collected relate.

2.12 “4 week Early Payment” means Customer Funds collected by You from the Client Account at any time from 4 weeks after the payment was collected but prior to the completion of the stay to which the Customer Funds collected relate .

2.13 Any reference to a specific statute includes any statutory extension, modification, amendment or re-enactment of such statute and any regulations or orders made thereunder and any general reference to “statute” or “statutes” includes all Acts of Parliament and any regulations, statutory instruments and/or orders made thereunder. Any reference to a clause, sub-clause or schedule means a clause or sub-clause of or schedule to this Agreement unless otherwise expressly stated. References to any gender include all other genders and to the singular includes the plural and vice versa. 

Use of the System:

3. Subject to your compliance at all times with the terms of this Agreement, We agree to;-

3.1 Provide access to the System. Nothing in this Agreement shall, however, impose any obligation on Us to provide access to, maintain or manage on your behalf any facility which at time forms part of the System or become liable in any way whatsoever for any bookings made or not made through the System. We will use our reasonable endeavours to provide access to and availability of the System at all reasonable times subject to maintenance and other factors, whether planned or unplanned, which require or result in the suspension or interruption of or any deficiency(ies) in the System or its operation in whole or part or your access to the same. No representation or guarantee is given that the operation of the System will be uninterrupted, continuous or error free. We have no liability to You in respect of any such occurrences or for any loss or damage of any nature whatsoever (including for the avoidance of doubt and not by way of limitation any loss of bookings) which You may suffer or incur as a result.      
 
3.2 Provide you with the ability to display your Accommodation prices and collect payment in Pounds Sterling, US Dollars or Euros. This choice can be changed on a booking by booking basis but for each booking, the price must be displayed and payment collected in the same currency. 

3.3 Market your Accommodation on the Website and on any other website(s) which are part of the Affiliate program. Allowing Us to market your Accommodation on all such websites is an obligation on Your part and a condition of our allowing You to use the System. It is not an option to use the System without allowing Us to market Your Accommodation on all such websites on Your behalf. Any bookings of Your Accommodation made through the System are subject to the payment of Commission. 

3.4 Accept credit or debit card payments via the System from Customers for Accommodation bookings and remit the same to You as more fully set out in this Agreement. 

3.5 Deposit Customers Funds in the Client Account as soon as reasonably possible after receipt and hold the same in the Client Account in accordance with the terms of this Agreement. 

Payment of Customers Funds to You

4.0 If this is your first payment collection, Customer Funds will only be available for payment to You the day after the stay of your first customer has ended and  28 days has passed since the first card payment for the booking was made irrespective of whether the booking has been completed or not. If this is no longer your first collection the rules outlined in 4.1 and 4.2 apply.

4.1 Customer Funds will be available for payment to You by Us after no less than 3 days after the booking has commenced for no additional charge or commission other than the Commission shown in the Schedule.

4.2 Customer Funds will be available for payment to You by Us before Customers have completed their stay at the Accommodation subject to payment of the additional charges and the credit limit  set out in the Schedule. The credit limit is the maximum amount of Customer Funds which may be paid to you in total in respect of bookings where the Customers have yet to complete their stay at the Accommodation. The credit limit may be changed where, in our reasonable discretion, we consider it appropriate to do so.

4.3 Customer Funds will be sent to You only when You make a valid payment request through the System and you have entered the correct banking details information.

4.4 In the case of accepted payment requests to an account held with a UK bank, We will transfer  the Customer Funds requested to You by BACS transfer . In the case of accepted payment requests to an account held with a non-UK bank, We will transfer the Customer Funds requested by EFT priority payment.

4.5 Payments to You will only be made in the currency the booking payment was made in by the Customer.

4.6 We will not be responsible for the collection from Customers and/or holding in the Client Account of any  charges which have not been entered as extra prices in the System.

Your Obligations to Us

Our Commission

5.You agree and acknowledge that:-

5.1 You will  pay Us Commission on every booking of Your Accommodation made via the System in accordance with the terms of this Agreement at the rate set out in the Schedule or such other rate as is agreed in writing between the parties.

5.2 We will become entitled to Commission on the full value of a booking when a booking is made i.e. when the Customer pays or authorises payment of the amount due at the time of booking and has agreed the rental contract.

5.3 We will be entitled to deduct the Commission due to Us from any Customer Funds. In practice, this means that when We transfer Customer Funds to you from the Client Account we will deduct any Commission owing to Us from the amount transferred.

Accommodation and the rental contract 

6. You agree, confirm and acknowledge that:-

6.1 The Accommodation and all services You contract with any Customer to provide will be provided with reasonable skill and care and that all persons provided or used by You (whether or not employed by You) in connection with the provision of the Accommodation will be appropriately qualified, experienced and capable of competently performing the work or jobs for which they are provided.

6.2 The Accommodation will at all times remain of a good and clean standard, in full working order and safe for occupation and use by Customers.

6.3 The Accommodation and all services You contract with any Customer to provide comply and will at all times comply in full with all applicable national, local, trade and other laws, regulations and codes of practice (including EU legislation where applicable) relating to hygiene, fire, safety and other standards for those staying at or using the Accommodation or contracted services and that You have and will at all times maintain in force the appropriate current certificates confirming such compliance.

6.4 You hold and will at all times maintain all necessary licenses, consents and permissions required by applicable national and/or local law in relation to the Accommodation and/or the contracted services.
6.5 The rental contract available for Your use on the System has been drafted on the basis of English law but is expressly governed by the law of the country where Your Accommodation is located and is subject to the exclusive jurisdiction of the courts of that country. Accordingly, the law which applies to You, Your Accommodation and the contract You enter into with Customers may impose different obligations and liabilities on You and You may be able to take advantage or have the benefit of different or additional defences, exclusions and/or limitations of liability to those set out in the rental contract on the System. Accordingly, the rental contract on the System may not correctly or fully state Your legal obligations and/or position and may not include all / some / any of the defences, exclusions or limitations available to You. Alternatively, the rental contract on the System may include defences, exclusions or limitations which You are not legally entitled to rely on.  Use of the rental contract on the System is entirely at Your own risk. It is Your sole responsibility to establish Your legal position and take whatever steps are appropriate or necessary to protect it (including entering into a supplementary rental agreement with Customers where appropriate). We have no liability whatsoever for any claims, loss, damage, costs, expenses, liabilities or other sums of whatever nature or description which You suffer or incur, directly or indirectly, as a result of Your use of the rental contract on the System, whether alone or in conjunction with any supplementary agreement(s).

6.6 You confirm that You own the Accommodation and have full and unrestricted power to enter into this Agreement. Where the Accommodation is owned by more than one person, all co-owners should enter into this Agreement. Where not all co-owners do so, the owner(s) who enter into this Agreement do so on behalf of all co-owners and confirm he / they have the full and unrestricted written authority of all other co-owners to do so.

6.7 Where You are not the owner or co-owner of the Accommodation but are acting as the agent of the owner(s),  You confirm that You  have the full and unrestricted written permission of all owners of the Accommodation to market and let the Accommodation for holiday purposes in accordance with this Agreement and that the owners have full knowledge of the terms of this Agreement.  The owners of the Accommodation will be treated as a party to this Agreement in addition to You and We are entitled to enforce all obligations contained in this Agreement against You and /or the owners (or any of them where there is more than one owner). As appropriate, references in this Agreement to “You” include the owner(s) of the Accommodation.

6.8 Where You are an owner but not the sole owner or all owners of the Accommodation, You confirm that You have the full and unrestricted written permission of all owners of the Accommodation to market and let the Accommodation for holiday purposes in accordance with this Agreement and that all the owners have full knowledge of the terms of this Agreement.  All owners of the Accommodation will be treated as a party to this Agreement in addition to You and We are entitled to enforce all obligations contained in this Agreement against You and /or any other owner(s) of the Accommodation. As appropriate, references in this Agreement to “You” include all owners of the Accommodation. 

System usage, Set up and handling Customers

7. You agree and confirm that:

7.1 You are responsible for the initial uploading of the descriptive details, prices and all other information relating to the Accommodation onto the System and at all times thereafter regularly and promptly maintaining, checking, updating and amending (if applicable) the same so that all information (including photographs) at all times remains accurate, complete and not misleading in any respect.

7.2 All prices entered onto the System by You relating to the Accommodation will at all times be up to date, accurate and not misleading in any way whatsoever.

7.3 You will upload the correct pricing, extras, discounting and payment terms applicable to all bookings for the Accommodation onto the System. You will be responsible for checking that the System settings you have chosen work as You intend. You will check that any booking request presented to You is correctly priced before accepting it. We accept no liability whatsoever for any claims, losses or damages (direct or indirect) of any description whatsoever suffered by any Customers or You arising out of inaccurate or incomplete pricing for any booking where you have accepted the booking request.

7.4 You will upload the correct cancellation charges applicable to bookings of the Accommodation onto the System.

7.5 You are solely responsible for the accuracy, legality, currency and compliance of all information (including written and pictorial descriptions) uploaded by You onto the System and/or otherwise provided to any Customer(s) and will be solely liable for any false, misleading, inaccurate, incomplete, infringing or other actionable information or material contained or referred to therein.
7.6 You confirm that You have prepared all descriptions and other material uploaded on the System and that all photographs used were taken by You or a member of Your family or are otherwise owned by You. You confirm that You will not upload any material of any description (including photographs) which infringes or may infringe the copyright or other intellectual property rights of any third party.

7.7 If you are not using the System exclusively for processing all your bookings, You will regularly and promptly update the dates on which the Accommodation is shown as available for let using the System. We accept no liability whatsoever for any claims, losses or damages (direct or indirect) of any description whatsoever suffered by any Customers or You arising out of inaccurate or incomplete availability dates except where this is due to a technical failure of the System.

7.8 You will  respond promptly and efficiently to any queries from Customers regarding the Accommodation and/or any booking whether received before or after bookings have been confirmed.

7.9 You will promptly notify Customers promptly of any alterations or amendments to Accommodation details both before and after bookings have been confirmed.

7.10 You will promptly notify the Customers affected if You have to cancel a booking.

7.11 You will promptly and sympathetically deal with any complaints received from Customers whether passed onto You by Us or received directly from Customers and respond to the same directly to the Customer(s) concerned within a reasonable time limit.

7.12 You will not use or attempt to use the System in any way or for any purpose other than its intended use and for its intended purpose which is to process bookings for your Accommodation.

7.13 You are not permitted to process credit or debit card payments on behalf of Customers or any other third party. Any breach or attempted breach of this prohibition will result in immediate termination of this Agreement.

7.14 Subject to the terms set out in the Schedule, You may require your Customers to pay a refundable breakage deposit of an amount specified by You which is collected with the full or final booking payment or, as an alternative where We provide You with the facility to do so, a non refundable breakage deposit waiver fee. Except as set out in the Schedule, We have no liability for any loss or damage to the Accommodation or its contents from any cause whatsoever. 

Amendments and Cancellations

8. You agree and acknowledge that:-

8.1 For all bookings where full payment has already been made  by credit or debit card to Us, all requests by Customers or by You for amendments which result in a higher or lower price becoming due for the booking of the Accommodation is beyond the scope of the System and will therefore be treated as a cancellation. We will then refund in full all monies already paid by the Customer to the credit or debit card used to make the booking and debit the Client Account in respect of the refunded monies. A fresh booking will then need to be made at the applicable price. The alternative is for You to make a separate arrangement directly with the Customer in relation to any additional payment or refund due.

8.2 Where We are notified of a cancellation by a Customer, We will calculate the applicable cancellation charge as set by You in the System and refund any monies due to the Customer after deduction of the applicable cancellation charges from monies paid by the Customer to the credit or debit card used to make the booking and debit the Client Account in respect of the refunded monies.

8.3 We accept no responsibility whatsoever for the non-payment of any monies due from any Customers nor for the collection of cancellation charges which exceed the total amount of monies already received from the Customers concerned as this is beyond the scope of the System.

8.4 In the event that You cancel or make material changes to a booking which the Customer is not prepared to accept, We are entitled (but not obliged) to assist the Customer in finding alternative accommodation. You also acknowledge that You are responsible for all losses, claims, expenses, costs and other sums incurred, suffered or made by a Customer arising out of Your cancellation or change of the booking and that We will have no responsibility or liability whatsoever to the Customer for such cancellation or change. For the avoidance of doubt, in the event of a cancellation or change of a booking by You, the indemnity set out in clause 12 will apply in relation to any sums we incur as a result including those which we pay on a goodwill or without prejudice basis without any legal obligation to do so. 

The Consequence of Cancellations

9.1 In the event of cancellation by either You or the Customer for whatever reason, We are still entitled to payment of our Commission on the full value of the booking together with our booking fee.
 
9.2 If a Customer cancels a confirmed booking, We will note our charges as sums owing to Us on your account and We will be entitled to payment of the same as set out in clause 9.3..

9.3 If You cancel a confirmed booking You will remain liable in full for the Commission due on the full value of the booking together with the cancellation charge set out in the Schedule. The Commission amount and the cancellation charge will be noted as sums owing to Us on your account and We will be entitled to deduct these and any other charges or sums due to Us from the next payment due to You from Us, or if there are no further payments to be made within a period of 1 month from the date the sums were noted on your account as described in this clause, We will invoice You for this amount. Payment in respect of any such invoice must be received within 7 days.

9.4 Any payments already received by You in respect of a booking You have cancelled must be promptly returned to Us or to the Customer if the Customer has paid You direct. 

Refunds and Chargebacks

10.1 Subject to clause 10.2, if We are obliged to refund any Customer(s) because of a credit card charge back, in accordance with the “money back guarantee” We provide to Customers or for any other reason and the relevant Customer Funds have already been remitted to You, You must promptly refund to Us all monies we have or are obliged to refund to the Customer, or if Customer Funds remain in the Client Account, You must promptly notify Us of any refunds to be made or which have been made direct to Customers. On receipt of such monies/notification, We will refund to the Customer(s) concerned all monies due in full. In all other cases, You will promptly refund all monies due to Customers for whatever reason direct to the Customers. For the avoidance of doubt, We are entitled to refund the Customer ourselves or from any Customer Funds in the Client Account in this situation irrespective of any notification or lack of notification or consent from You. Where We do so, it is Your sole responsibility to seek payment of all sums from the Customer which you allege should not have been refunded. Where We refund the Customer ourselves, clause 12 will apply. 

10.2 In the event of Us having to refund monies to a Customer due to a credit card chargeback whilst a dispute is ongoing, You agree and acknowledge that We are obliged and entitled to refund such monies as are charged back using the Customer Funds for the booking in question and shall have no further liability to You whatsoever.

10.3 You agree that if You wish to recoup any monies You feel You are entitled to from a Customer to whom We have refunded any monies, You will be solely responsible for pursuing the Customer direct for these, and not Us. 

Liability

11. You hereby acknowledge and agree that:

11.1 All Customers who make a booking for the Accommodation will have a direct contract with You and You will accept liability for that contract as the principal.
11.2 You have sole responsibility for all claims made by any Customer(s) in relation to or in connection with the Accommodation or any other service(s) You have contracted to provide or any booking of the Accommodation including, by way of example and not by way of limitation, responding to, handling and where appropriate paying compensation and/or refunds in respect of the same.

11.3 We will not be liable to You or any Customer for any loss or damage whatsoever or howsoever caused arising directly or indirectly in connection with this Agreement and/or the System, its use, application, support or otherwise, damage or corruption to other software or data or for loss of profit, business, revenue or goodwill except to the extent to which it is unlawful to exclude such liability.

11.4 We do not exclude liability for death or personal injury which is directly caused by the negligence of Us or any of our employees providing, in the case of employees, they were at the time acting within the course of their employment. 

Indemnity

12.1 You agree to indemnify and keep Us indemnified against and in respect of the full amount of all liabilities, claims, losses, expenses, costs (including legal costs on a full indemnity basis), damages, refunds and all other sums of whatever nature and of whatever description  (collectively “liabilities”) which are suffered or incurred by Us or for which We become liable or responsible and which arise, from any cause whatsoever, out of or in connection with this Agreement. For the avoidance of doubt and not by way of limitation, the liabilities covered by this indemnity shall include (but are not limited to) those arising, directly or indirectly, from any breach of this Agreement and/or any other agreement between You and Us by You and/or any act(s) and/or default(s) of You and/or any person(s) provided or used (directly or indirectly) by You (including your employees, agents, suppliers and sub-contractors).  For the avoidance of any doubt, this indemnity shall apply to any or all liabilities incurred or suffered by Us including those where there is no finding of negligence, breach of contract, breach of statutory duty or otherwise on Your part and the words “out of or in connection with this Agreement” shall be given the widest possible construction. This indemnity will survive and remain in full force and effect after the termination (for any reason) or expiry of this Agreement.

12.2 Without prejudice to the above You also agree to indemnify and keep Us indemnified (including our directors, officers, employees and agents) from and against any and all liability, damages, fines, losses, claims (including all  legal fees) expenses, costs and all other sums of whatever nature which We incur, suffer or become liable for as a result, directly or indirectly, of Your use of the System and /or any information or material uploaded by You on the System or otherwise provided or made available by You to any Customers. 

Insurance

13.1 You will at all times maintain (at Your own cost) a comprehensive insurance policy or policies to cover (with an adequate indemnity level):-

13.2 All risks relating to the use and/or occupation of the Accommodation normally covered by insurance including (including by way of example and not by way of limitation) destruction or damage of the Accommodation by any cause and all third party risks including cover for death, personal injury and illness of any Customer(s).

13.3 The full amount of all sums which may become payable under clauses 12.1 and 12.2.


Termination

14.1 This Agreement will continue in force indefinitely, but may be terminated:-

14.1.2 Immediately on Us giving You written notice (including by email) on You breaching this Agreement or any other agreement between You and Us and failing to remedy the said breach within 7 days (or such longer period as We may agree in writing) of being required to do so in writing by Us.

14.1.3 On Us giving You 28 days notice in writing with effect from the expiry of the said notice.

14.1.4 Immediately on Us giving written notice to You on the occurrence of any of the following events:-

14.1.4.1 On an order being made or an effective resolution being passed for the administration or the winding up of any business of which the letting of the Accommodation forms part or of which You are the owner or co-owner (including as shareholder) or which is otherwise relevant to the Accommodation or your performance of this Agreement (other than for the purpose(s) of re-organisation, reconstruction or amalgamation only without insolvency) or on You entering into a binding legal arrangement to pay your creditors less than the full amount due to them.

14.1.4.2 On You becoming bankrupt or insolvent or having a receiving order made against You.

14.1.4.3 On You suspending, ceasing or threatening to suspend or cease to carry on any business of which the letting of the Accommodation forms part (other than for the purpose(s) of re-organisation, reconstruction or amalgamation only without insolvency) or being unable to pay your debts as they fall due or on the appointment of an administrative or other receiver.

14.1.5 Immediately on You giving Us notice in writing (including by email) .

14.2 Save as set out in clause 15, termination of this Agreement shall not prejudice any rights of You or Us which are in existence prior to the effective date of termination.

14.3 You understand that it is possible to immediately turn off your access to the System thus making your Accommodation un-bookable and equally it can be turned back on again by You at your convenience.
14.4 We reserve the right to turn off, remove or disable your access to the System for your Accommodation, either temporarily or permanently for any of the following reasons.

14.4.1 We believe the details of your Accommodation or the settings You are using on the System are in any way misleading, confusing or will or may lead to complaint or error in the booking process.

14.4.2 You attempt to promote another website or enter an email address, phone number or other means of communication in the descriptive area of the System or elsewhere whether intended to deal directly with Customers or done unintentionally.

14.4.3 You enter any information or material in the descriptive area which in Our opinion is or may be in breach of copyright or subject to complaint by another party or on any basis is or may be fraudulent, offensive or misleading. 

Consequences of Termination

15. In the event of termination by either party in accordance with clause 14 the following provisions will apply.

15.1  Your access to the System will be terminated and will cease. We will cease to advertise your Accommodation and will remove it from the System thereby removing the facility to accept payments for any and all Accommodation.

15.2 In such cases where confirmed but yet to be performed booking contracts are in existence at the time of termination, We shall remit all monies received from the Customers for such bookings of Accommodation back to the Customer. You agree that You will then be responsible for obtaining all monies due for the Accommodation booking direct from the Customer. We shall have no further liability towards You. 

Customer details

16.You acknowledge that We are entitled to use Customers’ personal and other details in any of the ways and for any of the purposes set out in our Privacy Statement (found on our website) as amended and updated from time to time or as otherwise permitted by law. You also acknowledge that this shall be the case regardless of whether We obtained the details in question from the Customer direct or from You. You also confirm that, in relation to any personal or other details relating to Customers and enquirers (whether potential, present or past) in your possession You shall at all times, including all times after the termination of this Agreement, process such data in compliance with the obligations of a Data Controller under the Data Protection Act 1998 and any amendments thereto. Furthermore, You shall not at any time, including any times after the termination of this Agreement, send any marketing or promotional material or communications to individuals whose personal or other contact details You hold except in accordance with all applicable legislation in force at the relevant time (including but not limited to the Data Protection Act 1998 and the Privacy and Electronic Communications Regulations 2003 and all amendments thereto).

Copyright, Patents, Trade Marks and Other Intellectual Property Rights

17.1 You acknowledge that all copyright, trade marks, trade names, patents, domain names and other intellectual property rights of whatever nature created, developed, subsisting or used in or in connection with the System are and shall remain the sole property of Rurenter.ru Ltd. You shall not during the subsistence of this Agreement or at any time after the completion, expiry or termination of this Agreement in any way use or permit the use of the same save as expressly permitted by this Agreement or question or dispute the ownership by Rurenter.ru Ltd thereof.

17.2 In the event that new inventions, designs or processes or other intellectual property rights of any description evolve or come into existence in the performance of or as a result of this Agreement, You acknowledge that the same shall be the property of Rurenter.ru Ltd unless otherwise agreed in writing by Rurenter.ru Ltd. 